import { describe, expect, it } from "vitest";
import { suggestColumnMapping, detectHeaderRowIndex } from "./column-detection";

describe("suggestColumnMapping", () => {
  it("matches common bank-export header names", () => {
    const suggestions = suggestColumnMapping([
      "Transaction Date",
      "Narration",
      "Withdrawal",
      "Deposit",
      "Txn ID",
    ]);

    expect(suggestions).toContainEqual({ sourceColumn: "Transaction Date", targetField: "date" });
    expect(suggestions).toContainEqual({ sourceColumn: "Narration", targetField: "description" });
    expect(suggestions).toContainEqual({ sourceColumn: "Withdrawal", targetField: "expenseAmount" });
    expect(suggestions).toContainEqual({ sourceColumn: "Deposit", targetField: "incomeAmount" });
    expect(suggestions).toContainEqual({ sourceColumn: "Txn ID", targetField: "referenceId" });
  });

  it("matches a simple Amount + Type export", () => {
    const suggestions = suggestColumnMapping(["Date", "Amount", "Type", "Category"]);

    expect(suggestions).toContainEqual({ sourceColumn: "Date", targetField: "date" });
    expect(suggestions).toContainEqual({ sourceColumn: "Amount", targetField: "amount" });
    expect(suggestions).toContainEqual({ sourceColumn: "Type", targetField: "type" });
    expect(suggestions).toContainEqual({ sourceColumn: "Category", targetField: "category" });
  });

  it("is case- and punctuation-insensitive", () => {
    const suggestions = suggestColumnMapping(["  TRANSACTION-DATE  ", "ref_no"]);

    expect(suggestions).toContainEqual({
      sourceColumn: "  TRANSACTION-DATE  ",
      targetField: "date",
    });
    expect(suggestions).toContainEqual({ sourceColumn: "ref_no", targetField: "referenceId" });
  });

  it("never assigns a target field to more than one column", () => {
    // Both headers alias to "date" — only the first (left-most) should win.
    const suggestions = suggestColumnMapping(["Date", "Value Date", "Posting Date"]);

    const dateMatches = suggestions.filter((s) => s.targetField === "date");
    expect(dateMatches).toHaveLength(1);
    expect(dateMatches[0].sourceColumn).toBe("Date");
  });

  it("never assigns a column to more than one target field", () => {
    // A header can only satisfy one alias list even if it happens to be
    // considered under an earlier target field first.
    const suggestions = suggestColumnMapping(["Amount"]);
    const usingAmountColumn = suggestions.filter((s) => s.sourceColumn === "Amount");
    expect(usingAmountColumn).toHaveLength(1);
  });

  it("leaves unrecognized headers unmapped", () => {
    const suggestions = suggestColumnMapping(["Foo Bar Baz", "Something Else"]);
    expect(suggestions).toHaveLength(0);
  });

  it("returns an empty array for an empty header list", () => {
    expect(suggestColumnMapping([])).toEqual([]);
  });

  it("ignores blank header strings", () => {
    const suggestions = suggestColumnMapping(["", "   ", "Date"]);
    expect(suggestions).toEqual([{ sourceColumn: "Date", targetField: "date" }]);
  });
});

describe("detectHeaderRowIndex", () => {
  it("returns row 0 for an ordinary, preamble-free file", () => {
    const rows = [
      ["Date", "Amount", "Type", "Category"],
      ["2026-01-05", "100", "INCOME", "Sales"],
      ["2026-01-06", "50", "EXPENSE", "Supplies"],
    ];
    expect(detectHeaderRowIndex(rows)).toBe(0);
  });

  it("skips a statement-style preamble to find the real header row", () => {
    // Mirrors eSewa's actual export shape: title, period, generator
    // metadata, blank rows, then the real header row.
    const rows = [
      ["Statement Report", "", "", "", "", "", "", ""],
      ["", "", "", "", "", "", "", ""],
      ["From Date", "Mon Aug 24 2026", "To Date", "Mon Aug 31 2026", "", "", "", ""],
      ["Generated On", "2026-08-31 12:40:37", "Status", "ALL", "", "", "", ""],
      ["Channel", "ALL", "Dr/Cr", "ALL", "", "", "", ""],
      ["Generated by", "9814944091", "", "", "", "", "", ""],
      ["", "", "", "", "", "", "", ""],
      ["", "", "", "", "", "", "", ""],
      [
        "Reference Code",
        "Date Time",
        "Description",
        "Dr.",
        "Cr.",
        "Status",
        "Balance (NPR)",
        "Channel",
      ],
      ["1PSY573", "2026-08-29 20:40:00.0", "Paid for OHO CAKE", "650.0", "0.0", "COMPLETE", "249.9", "App"],
    ];
    expect(detectHeaderRowIndex(rows)).toBe(8);
  });

  it("falls back to the densest row when no aliases match anywhere", () => {
    const rows = [
      ["Some Title"],
      ["Foo", "Bar", "Baz", "Qux"],
      ["1", "2", "3", "4"],
    ];
    expect(detectHeaderRowIndex(rows)).toBe(1);
  });

  it("skips leading blank rows", () => {
    const rows = [
      ["", "", ""],
      ["", "", ""],
      ["Date", "Amount", "Type"],
    ];
    expect(detectHeaderRowIndex(rows)).toBe(2);
  });

  it("returns 0 for a completely blank sheet rather than throwing", () => {
    const rows = [
      ["", ""],
      ["", ""],
    ];
    expect(detectHeaderRowIndex(rows)).toBe(0);
  });
});
